import { appendFileSync, copyFileSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { afterEach, describe, expect, it } from "vitest";

let temporaryDirectory: string | undefined;
const changelogPath = resolve("CHANGELOG.md");
const verifyScript = resolve("scripts/verify-changelog.mjs");

describe("generated changelog", () => {
  afterEach(() => {
    if (temporaryDirectory) rmSync(temporaryDirectory, { recursive: true, force: true });
    temporaryDirectory = undefined;
  });

  it("changelog_markdown_is_generated", () => {
    const changelog = readFileSync(changelogPath, "utf8");
    expect(changelog).toContain("Generated by pnpm changelog:generate from src/content/releases.ts");
  });

  it("changelog_generation_is_deterministic", () => {
    const first = readFileSync(changelogPath, "utf8");
    const result = spawnSync(process.execPath, [verifyScript], { encoding: "utf8" });
    expect(result.status, result.stderr).toBe(0);
    expect(readFileSync(changelogPath, "utf8")).toBe(first);
  });

  it("changelog_verify_detects_drift", () => {
    temporaryDirectory = mkdtempSync(join(tmpdir(), "stugx-changelog-"));
    const changedPath = join(temporaryDirectory, "CHANGELOG.md");
    copyFileSync(changelogPath, changedPath);
    appendFileSync(changedPath, "\nmanual drift\n", "utf8");
    const result = spawnSync(process.execPath, [verifyScript, "--file", changedPath], { encoding: "utf8" });
    expect(result.status).not.toBe(0);
  });

  it("build_version_must_exist_in_registry", () => {
    const result = spawnSync(process.execPath, [verifyScript], {
      encoding: "utf8",
      env: { ...process.env, STUGX_BUILD_VERSION: "9.9.9" }
    });
    expect(result.status).not.toBe(0);
  });

  it("markdown_uses_canonical_repository_url", () => {
    expect(readFileSync(changelogPath, "utf8")).toContain("https://github.com/LMstugx/stugx-casl");
  });

  it("markdown_uses_public_pages_url", () => {
    expect(readFileSync(changelogPath, "utf8")).toContain("https://stugx-casl.pages.dev/");
  });

  it("markdown_has_no_local_paths", () => {
    expect(readFileSync(changelogPath, "utf8")).not.toMatch(/[A-Za-z]:\\|file:\/\//);
  });

  it("markdown_has_no_wip_branch_reference", () => {
    expect(readFileSync(changelogPath, "utf8")).not.toMatch(/phase17b-cloudflare-wip|feature\//i);
  });
});
