import { describe, expect, it } from "vitest";
import gitignore from "../../.gitignore?raw";
import packageJsonRaw from "../../package.json?raw";
import visualReviewDoc from "../../docs/visual-review.md?raw";
import captureScript from "../../scripts/capture-visual-review.ps1?raw";
import serveScript from "../../scripts/serve-visual-review.ps1?raw";
import visualReviewSpec from "../../tests/e2e/visual-review.spec.ts?raw";

describe("visual review screenshot gallery setup", () => {
  it("visual_review_spec_exists", () => {
    expect(visualReviewSpec).toContain("visual review screenshot gallery");
    expect(visualReviewSpec).toContain('name: "1280x720"');
    expect(visualReviewSpec).toContain("project-overview.png");
    expect(visualReviewSpec).toContain("ui-casl-diagnostic-error.png");
    expect(visualReviewSpec).toContain("ui-cpp-diagnostic-error.png");
    expect(visualReviewSpec).toContain("diagnostics-en-casl.png");
    expect(visualReviewSpec).toContain("diagnostics-ja-casl.png");
    expect(visualReviewSpec).toContain("diagnostics-zh-cn-casl.png");
    expect(visualReviewSpec).toContain("diagnostics-en-cpp.png");
    expect(visualReviewSpec).toContain("diagnostics-ja-cpp.png");
    expect(visualReviewSpec).toContain("diagnostics-zh-cn-cpp.png");
    expect(visualReviewSpec).toContain("diagnostic-range-casl.png");
    expect(visualReviewSpec).toContain("diagnostic-range-cpp.png");
    expect(visualReviewSpec).toContain("diagnostics-parser-en.png");
    expect(visualReviewSpec).toContain("diagnostics-parser-ja.png");
    expect(visualReviewSpec).toContain("diagnostics-parser-zh-cn.png");
    expect(visualReviewSpec).toContain("diagnostic-p2-en.png");
    expect(visualReviewSpec).toContain("diagnostic-p2-ja.png");
    expect(visualReviewSpec).toContain("diagnostic-p2-zh-cn.png");
    expect(visualReviewSpec).toContain("diagnostic-p2-related-location.png");
    expect(visualReviewSpec).toContain("diagnostic-long-technical-token.png");
    expect(visualReviewSpec).toContain("diagnostics-long-token.png");
    expect(visualReviewSpec).toContain("diagnostics-1280-ja.png");
    expect(visualReviewSpec).toContain("diagnostics-1280-zh-cn.png");
    expect(visualReviewSpec).toContain("diagnostic-related-location.png");
    expect(visualReviewSpec).toContain("diagnostic-eof.png");
    expect(visualReviewSpec).toContain("diagnostic-ja-long.png");
    expect(visualReviewSpec).toContain("diagnostic-zh-cn-long.png");
    expect(visualReviewSpec).toContain("diagnostic-1280.png");
    expect(visualReviewSpec).toContain("ui-stopped-state.png");
    expect(visualReviewSpec).toContain("ui-keyboard-focus.png");
    expect(visualReviewSpec).toContain("ui-locale-selector.png");
    expect(visualReviewSpec).toContain("locale-en-1280.png");
    expect(visualReviewSpec).toContain("locale-ja-1280.png");
    expect(visualReviewSpec).toContain("locale-zh-cn-1280.png");
    expect(visualReviewSpec).toContain("locale-ja-output-dock.png");
    expect(visualReviewSpec).toContain("locale-zh-cn-inspector-memory.png");
    expect(visualReviewSpec).toContain("locale-en-cpu-flow.png");
    expect(visualReviewSpec).toContain("locale-ja-cpu-flow.png");
    expect(visualReviewSpec).toContain("locale-zh-cn-cpu-flow.png");
    expect(visualReviewSpec).toContain("locale-ja-register-stack.png");
    expect(visualReviewSpec).toContain("locale-zh-cn-register-stack.png");
    expect(visualReviewSpec).toContain("locale-ja-code-machine.png");
    expect(visualReviewSpec).toContain("locale-zh-cn-code-machine.png");
    expect(visualReviewSpec).toContain("locale-ja-signal-probe.png");
    expect(visualReviewSpec).toContain("locale-zh-cn-stack-frame.png");
    expect(visualReviewSpec).toContain("casl-gr2-ld.png");
    expect(visualReviewSpec).toContain("enterCircuitFocusMode");
    expect(visualReviewSpec).toContain("logical-add-compare-jov.png");
    expect(visualReviewSpec).toContain("shift-operations-circuit.png");
    expect(visualReviewSpec).toContain("shift-operations-machine-code.png");
    expect(visualReviewSpec).toContain("stack-preview-focus.png");
    expect(visualReviewSpec).toContain("stack-frame-view-preview.png");
    expect(visualReviewSpec).toContain("push-pop-stack-circuit.png");
    expect(visualReviewSpec).toContain("push-pop-stack-machine-code.png");
    expect(visualReviewSpec).toContain("call-return-call.png");
    expect(visualReviewSpec).toContain("call-return-ret-stack.png");
    expect(visualReviewSpec).toContain("call-return-finish.png");
    expect(visualReviewSpec).toContain("call-return-machine-code.png");
    expect(visualReviewSpec).toContain("nested-call-return.png");
    expect(visualReviewSpec).toContain("cpp-function-call-generated-casl.png");
    expect(visualReviewSpec).toContain("cpp-function-call-trace.png");
    expect(visualReviewSpec).toContain("cpp-function-call-machine-code.png");
    expect(visualReviewSpec).toContain("cpp-function-argument-generated-casl.png");
    expect(visualReviewSpec).toContain("cpp-function-argument-trace.png");
    expect(visualReviewSpec).toContain("cpp-function-argument-machine-code.png");
    expect(visualReviewSpec).toContain("cpp-function-arguments-generated-casl.png");
    expect(visualReviewSpec).toContain("cpp-function-arguments-trace.png");
    expect(visualReviewSpec).toContain("cpp-function-arguments-machine-code.png");
    expect(visualReviewSpec).toContain("page.screenshot");
  });

  it("capture_visual_review_script_exists", () => {
    expect(captureScript).toContain("pnpm visual:review");
    expect(captureScript).toContain("artifacts\\visual-review");
    expect(captureScript).toContain("index.html");
  });

  it("serve_visual_review_script_exists", () => {
    expect(serveScript).toContain("http.server");
    expect(serveScript).toContain("Local URL");
    expect(serveScript).toContain("LAN URL");
    expect(serveScript).toContain("Stop-Process");
  });

  it("visual_review_docs_exist", () => {
    expect(visualReviewDoc).toContain("Visual Review Screenshot Gallery");
    expect(visualReviewDoc).toContain("pnpm visual:capture");
    expect(visualReviewDoc).toContain("phone");
    expect(visualReviewDoc).toContain("Memory target state points to the active memory row");
    expect(visualReviewDoc).toContain("Active wires do not use terminal arrows");
    expect(visualReviewDoc).toContain("visual-review-static");
    expect(visualReviewDoc).toContain("freeze that animation");
    expect(visualReviewDoc).toContain("Junction dots are disabled by default");
    expect(visualReviewDoc).toContain("Memory-side circular terminal markers");
    expect(visualReviewDoc).toContain("active-flow wires only");
    expect(visualReviewDoc).toContain("Inspector Memory uses bounded internal scrolling");
    expect(visualReviewDoc).toContain("advanced UI design-system foundation");
    expect(visualReviewDoc).toContain("Phase 13B applies");
    expect(visualReviewDoc).toContain("Phase 13C adds keyboard, contrast");
    expect(visualReviewDoc).toContain("shared token vocabulary");
    expect(visualReviewDoc).toContain("Toolbar actions are visually grouped");
    expect(visualReviewDoc).toContain("Selected, active execution, changed");
    expect(visualReviewDoc).toContain("FramePlan and slot-relation panels");
    expect(visualReviewDoc).toContain("Empty states use compact shared wording");
    expect(visualReviewDoc).toContain("DATA BUS");
    expect(visualReviewDoc).toContain("LD / ST data-bypass paths avoid the ALU body");
    expect(visualReviewDoc).toContain("ST writeback lands at the Memory row edge");
    expect(visualReviewDoc).toContain("Memory data flow uses short row stubs");
    expect(visualReviewDoc).toContain("Signal Probe is compact");
    expect(visualReviewDoc).toContain("Stack Preview is compact");
    expect(visualReviewDoc).toContain("active for stack instructions and stack-aware returns");
    expect(visualReviewDoc).toContain("PUSH / POP screenshots show");
    expect(visualReviewDoc).toContain("CALL / RET screenshots show");
    expect(visualReviewDoc).toContain("Circuit Focus screenshots include Program, Display, Current Instruction");
    expect(visualReviewDoc).toContain("stack-preview-focus.png");
    expect(visualReviewDoc).toContain("stack-frame-view-preview.png");
    expect(visualReviewDoc).toContain("ui-casl-diagnostic-error.png");
    expect(visualReviewDoc).toContain("ui-cpp-diagnostic-error.png");
    expect(visualReviewDoc).toContain("diagnostics-ja-1280.png");
    expect(visualReviewDoc).toContain("diagnostics-zh-cn-1280.png");
    expect(visualReviewDoc).toContain("ui-stopped-state.png");
    expect(visualReviewDoc).toContain("ui-keyboard-focus.png");
    expect(visualReviewDoc).toContain("ui-locale-selector.png");
    expect(visualReviewDoc).toContain("locale-en-1280.png");
    expect(visualReviewDoc).toContain("locale-ja-1280.png");
    expect(visualReviewDoc).toContain("locale-zh-cn-1280.png");
    expect(visualReviewDoc).toContain("locale-ja-output-dock.png");
    expect(visualReviewDoc).toContain("locale-zh-cn-inspector-memory.png");
    expect(visualReviewDoc).toContain("push-pop-stack-circuit.png");
    expect(visualReviewDoc).toContain("push-pop-stack-machine-code.png");
    expect(visualReviewDoc).toContain("call-return-call.png");
    expect(visualReviewDoc).toContain("call-return-ret-stack.png");
    expect(visualReviewDoc).toContain("call-return-finish.png");
    expect(visualReviewDoc).toContain("call-return-machine-code.png");
    expect(visualReviewDoc).toContain("nested-call-return.png");
    expect(visualReviewDoc).toContain("cpp-function-call-generated-casl.png");
    expect(visualReviewDoc).toContain("cpp-function-call-trace.png");
    expect(visualReviewDoc).toContain("cpp-function-call-machine-code.png");
    expect(visualReviewDoc).toContain("cpp-function-argument-generated-casl.png");
    expect(visualReviewDoc).toContain("cpp-function-argument-trace.png");
    expect(visualReviewDoc).toContain("cpp-function-argument-machine-code.png");
    expect(visualReviewDoc).toContain("cpp-function-arguments-generated-casl.png");
    expect(visualReviewDoc).toContain("cpp-function-arguments-trace.png");
    expect(visualReviewDoc).toContain("cpp-function-arguments-machine-code.png");
  });

  it("package_json_has_visual_review_scripts", () => {
    const packageJson = JSON.parse(packageJsonRaw) as { scripts: Record<string, string> };

    expect(packageJson.scripts["visual:review"]).toContain("E2E_BACKEND='visual-review'");
    expect(packageJson.scripts["visual:review"]).toContain("playwright test tests/e2e/visual-review.spec.ts");
    expect(packageJson.scripts["visual:capture"]).toContain("capture-visual-review.ps1");
    expect(packageJson.scripts["visual:serve"]).toContain("serve-visual-review.ps1");
  });

  it("gitignore_excludes_visual_review_artifacts", () => {
    expect(gitignore).toContain("artifacts/visual-review/");
    expect(gitignore).toContain("artifacts/screenshots/");
  });
});
